// app/layout.tsx
import { ReactNode } from "react";
import ReduxProvider from "./ReduxProvider"; 
import { Geist, Geist_Mono, Cormorant_Garamond } from "next/font/google";
import "./globals.css";

const cormorant_garamond = Cormorant_Garamond({ weight: ["400","500","600","700"], subsets: ["latin"], variable: "--font-cormorant-garamond" });
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`bg-[#FAFAFA] ${geistSans.variable} ${geistMono.variable} ${cormorant_garamond.variable} antialiased`}>
        {/* Wrap children with client-only ReduxProvider */}
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
